# Shell script that accepts file names specified as arguments and creates a
# shell script that contains this file as well as the code to recreate these
# files. Thus if the script generated by your script is executed, it would
# recreate the original files

if [ $# -eq 0 ]
then
    echo "No arguments"
    exit
fi

for i in $*
do
    echo "cat >$i << endf" >> cr.sh
    cat $i >> cr.sh
    echo "endf" >> cr.sh
done